name: Start release

on: create

jobs:
  debug:
    runs-on: ubuntu-18.04
    steps:
    - run: echo ${{ toJson(github.event) }}

  kickoff:
    if: startsWith(github.event.create.ref, 'refs/heads/release-')
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.DEPLOYMENT_TOKEN }}
    - name: Configure git
      run: |
        git config --local user.email bot@cjones.org
        git config --local user.name "Row Bot"
    - name: Calculate versions
      id: version
      run: |
        CURRENT=$(basename ${{ github.ref }})
        NAME=$(echo ${CURRENT} | sed 's/release-//')
        NUMBER=$(echo ${NAME} | sed -E -e 's/[^0-9.]+/./g' -e 's/\.+/./g' -e 's/^\.//' -e 's/\.$//')
        NEXT=$(echo ${NUMBER} | awk -F. -v OFS=. '{$NF++;print}')
        echo "::set-output name=current::${CURRENT}"
        echo "::set-output name=tag::${NAME}"
        echo "::set-output name=dewey::${NUMBER}"
        echo "::set-output name=next::${NEXT}"
    - name: Edit version
      run: echo "${{ steps.version.outputs.dewey }}" > version
    - run: git add version
    - run: git commit -m "Setting version to ${{ steps.version.outputs.tag }}"
    - run: git push
    - name: Create PR
      run: |
        curl --silent --show-error --fail -X POST \
          -H "Authorization: token ${{ github.token }}" \
          -H "Content-Type: application/json" \
          --data '{"title": "Release ${{ steps.version.outputs.tag }}",
            "head": "${{ github.ref }}",
            "base": "master",
            "body": "The release will be built when this PR is merged."
            }' \
          https://api.github.com/repos/${{ github.repository }}/pulls
