name: test
on:
  push:
    tags:
    - foo-*
env:
  FOO: bar
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: echo "::set-env name=BAR::${FOO}2"
    - run: env | sort
    - uses: IronCoreLabs/ironhide-actions/decrypt@master
      with:
        keys: ${{ secrets.IRONHIDE_KEYS }}
        input: foo.txt.iron
    - run: cat foo.txt
